### ISSUE TITLE
isochroneMulti issue

### ISSUE THREAD

**Issue by msrickettsOS** [datasciencecampus/access-to-services#12]
Hi,

I'm encountering an issue with isochroneMulti whereby the isochrones are created (trialing with demo .csv data) followed by this error message: 

Error in -c(originPoints_removed_list): invalid argument to unary operator.

Thanks,

Matt

**Comment by mshodge** [comment]
Hi Matt.

Thanks for highlighting! All should be resolved in the latest release. Install the package as you did before and let me know if the error persists :)

Michael

**Comment by msrickettsOS** [comment]
All fixed!

Thanks so much for the swift fix.

Matt
